language: cpp

compiler:
  - gcc

build: make

before_script:
  - mkdir build
  - cd build
  - cmake ..

# Install dependencies
install:
  - sudo apt-get update -qq
  - sudo apt-get install cppcheck
  - sudo apt-get install libsdl-dev

script: make

after_success:
  - ./CompGrafica
